yf_tickers = {
    "HIKAL.NS": "Hikal Ltd",
    "BALRAMCHIN.NS": "Balrampur Chini Mills Ltd",
    "ADANIPORTS.NS": "Adani Ports & Special Economic Zone Ltd",
    "ADANIGREEN.NS": "Adani Green Energy Ltd",
    "RELIANCE.NS": "Reliance Industries Ltd",
    "KOTAKBANK.NS": "Kotak Mahindra Bank Ltd",
    "AXISBANK.NS": "Axis Bank Ltd",
    "HINDUNILVR.NS": "Hindustan Unilever Ltd",
    "SBIN.NS": "State Bank of India",
    "INFY": "Infosys Ltd",
    "TCS.NS": "Tata Consultancy Services Ltd",
    "TMCV.NS": "Tata Motors Commercial Vehicles",
    "TMPV.NS": "Tata Motors Passenger Vehicles",
    "IRFC.NS": "Indian Railway Finance Corporation Ltd",
    "WEBELSOLAR.NS": "Websol Energy System Ltd",
    "EASEMYTRIP.NS": "Easy Trip Planners Ltd",
    "ASIANPAINT.NS": "Asian Paints Ltd",
    "BAJFINANCE.NS": "Bajaj Finance Ltd",
    "BAJAJFINSV.NS": "Bajaj Finserv Ltd",
    "ICICIBANK.NS": "ICICI Bank Ltd",
    "TITAN.NS": "Titan Company Ltd",
    "DIVISLAB.NS": "Divi's Laboratories Ltd",
    "BERGEPAINT.NS": "Berger Paints India Ltd",
    "IDFCFIRSTB.NS": "IDFC First Bank Ltd",
    "HDFCBANK.NS": "HDFC Bank Ltd",
    "ITC.NS": "ITC Ltd",
    "^NSEI": "Nifty 50"
}